import { jsPDF } from "jspdf";
import moment from "moment";

export function generateReceiptPDF(transaction) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  // Dark header background
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageW, 55, "F");

  // Brand name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont("helvetica", "bold");
  doc.text("Apex Bank", 20, 22);

  // Tagline
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 174, 192);
  doc.text("Transaction Receipt", 20, 30);

  // Status badge area
  const isCredit = transaction.type === "deposit" || transaction.type === "transfer_in";
  const statusColor = transaction.status === "completed" ? [16, 185, 129] :
                      transaction.status === "pending"   ? [245, 158, 11]  : [239, 68, 68];
  doc.setFillColor(...statusColor);
  doc.roundedRect(pageW - 50, 16, 36, 10, 2, 2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  const statusText = (transaction.status || "pending").toUpperCase();
  doc.text(statusText, pageW - 50 + 18, 22.5, { align: "center" });

  // Amount
  doc.setFontSize(11);
  doc.setTextColor(160, 174, 192);
  doc.setFont("helvetica", "normal");
  doc.text("Amount", 20, 44);
  doc.setFontSize(22);
  doc.setTextColor(isCredit ? "#10B981" : "#ffffff");
  doc.setFont("helvetica", "bold");
  const sign = isCredit ? "+" : "-";
  doc.text(`${sign}$${(transaction.amount || 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`, 20, 53);

  // Reference & Date on right
  doc.setFontSize(8);
  doc.setTextColor(160, 174, 192);
  doc.setFont("helvetica", "normal");
  doc.text(`Ref: ${transaction.reference_id || transaction.id?.slice(0, 12) || "N/A"}`, pageW - 20, 44, { align: "right" });
  doc.text(moment(transaction.created_date).format("MMM DD, YYYY h:mm A"), pageW - 20, 50, { align: "right" });

  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(20, 65, pageW - 20, 65);

  // Section: Transaction Details
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction Details", 20, 76);

  const fields = [
    ["Transaction ID", transaction.id || "—"],
    ["Type", (transaction.type || "").replace("_", " ").replace(/\b\w/g, l => l.toUpperCase())],
    ["Description", transaction.description || "—"],
    ["Recipient / Address", transaction.recipient || "—"],
    ["Currency", transaction.currency || "USD"],
    ["Fee", `$${(transaction.fee || 0).toFixed(2)}`],
    ["Total Deducted", `$${((transaction.amount || 0) + (transaction.fee || 0)).toFixed(2)}`],
    ["Status", (transaction.status || "—").toUpperCase()],
    ["Date & Time", moment(transaction.created_date).format("MMMM DD, YYYY [at] h:mm A")],
    ["Reference ID", transaction.reference_id || "—"],
  ];

  let y = 86;
  fields.forEach(([label, value], i) => {
    const bg = i % 2 === 0;
    if (bg) {
      doc.setFillColor(248, 250, 252);
      doc.rect(20, y - 5, pageW - 40, 11, "F");
    }
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.setFont("helvetica", "normal");
    doc.text(label, 24, y);
    doc.setTextColor(17, 24, 39);
    doc.setFont("helvetica", "bold");
    const val = String(value).length > 50 ? String(value).slice(0, 47) + "..." : String(value);
    doc.text(val, pageW - 24, y, { align: "right" });
    y += 11;
  });

  // Footer divider
  y += 6;
  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageW - 20, y);
  y += 10;

  // Footer text
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.setFont("helvetica", "normal");
  doc.text("This receipt is auto-generated by Apex Bank. For disputes, contact support@apexbank.com", pageW / 2, y, { align: "center" });
  doc.text(`Generated on ${moment().format("MMMM DD, YYYY [at] h:mm A")}`, pageW / 2, y + 6, { align: "center" });

  // Watermark for non-completed
  if (transaction.status !== "completed") {
    doc.setTextColor(239, 68, 68);
    doc.setFontSize(60);
    doc.setFont("helvetica", "bold");
    doc.setGState(doc.GState({ opacity: 0.06 }));
    doc.text(transaction.status?.toUpperCase() || "PENDING", pageW / 2, 180, { align: "center", angle: 35 });
    doc.setGState(doc.GState({ opacity: 1 }));
  }

  const fileName = `ApexBank-Receipt-${transaction.reference_id || transaction.id?.slice(0, 8) || "TX"}.pdf`;
  doc.save(fileName);
}